export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SECCESS: "LOGIN_SECCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_USER: "LOGIN_USER",
    USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SECCESS: "LOGOUT_SECCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
    SIGNUP_REQUEST: "SIGNUP_REQUEST",
    SIGNUP_SECCESS: "SIGNUP_SECCESS",
    SIGNUP_FAILURE: "SIGNUP_FAILURE",

}


export const userConstansts = {
    GET_USER_BY_REQUEST: "GET_USER_BY_REQUEST",
    GET_USER_BY_SECCESS: "GET_USER_BY_SECCESS",
    GET_USER_BY_FAILURE: " GET_USER_BY_FAILUR",
}

export const workspaceConstants = {
    GET_WORKSPACE_REQUEST: "GET_WORKSPACE_REQUEST",
    GET_WORKSPACE_SECCESS: "GET_WORKSPACE_SECCESS",
    GET_WORKSPACE_FAILURE: "GET_WORKSPACE_FAILURE",
    SET_WORKSPACE_REQUEST: "SET_WORKSPACE_REQUEST",
    SET_WORKSPACE_SECCESS: "SET_WORKSPACE_SECCESS",
    SET_WORKSPACE_FAILURE: "SET_WORKSPACE_FAILURE",
}

export const programsConstants = {
    LIST_PROGRAMS_SECCESS: "LIST_PROGRAMS_SECCESS",
    LIST_PROGRAMS_FAILURE: "LIST_PROGRAMS_FAILURE",
}